---
dependency:
  name: galaxy

driver:
  name: vagrant

platforms:
  - name: instance
    box: ubuntu/focal64
    memory: 1024
    cpu: 1

provisioner:
  name: ansible
  ANSIBLE_VERBOSITY: 3

verifier:
  name: ansible
