---
- name: Verify
  hosts: all
  become: true
  gather_facts: false
  vars:
    bitcoind_version: 26.0

  tasks:
    - name: "Retrieve information from /usr/local/bitcoin-core-{{ bitcoind_version }}"
      ansible.builtin.stat:
        path: "/usr/local/bin/{{ item }}"
      register: bitcoind_bins
      with_items:
        - bitcoin-cli
        - bitcoin-qt
        - bitcoin-tx
        - bitcoin-util
        - bitcoin-wallet
        - bitcoind
        - test_bitcoin

    - name: "Test that binaries were copied correctly for Bitcoin Core v{{ bitcoind_version }}"
      ansible.builtin.assert:
        that:
          - item.stat.exists
          - item.stat.executable
          - item.stat.pw_name == 'root'
          - item.stat.gr_name == 'root'
          - item.stat.mode == '0755'
      with_items: "{{ bitcoind_bins.results }}"
