---
- name: Verify
  hosts: all
  become: true
  gather_facts: false
  vars:
    bitcoind_implementation: "{{ lookup('env', 'BITCOIND_IMPL') | default('core', true) }}"
    bitcoind_version: "{{ lookup('env', 'BITCOIND_VERSION') | default('30.2', true) }}"
    # Core 30.x: bitcoin wrapper replaces test_bitcoin
    # Knots 29.x: still has test_bitcoin, no bitcoin wrapper
    _core_binaries:
      - bitcoin
      - bitcoin-cli
      - bitcoin-qt
      - bitcoin-tx
      - bitcoin-util
      - bitcoin-wallet
      - bitcoind
    _knots_binaries:
      - bitcoin-cli
      - bitcoin-qt
      - bitcoin-tx
      - bitcoin-util
      - bitcoin-wallet
      - bitcoind
      - test_bitcoin

  tasks:
    - name: "Retrieve information from /usr/local/bin/*"
      ansible.builtin.stat:
        path: "/usr/local/bin/{{ item }}"
      register: bitcoind_bins
      with_items: "{{ _core_binaries if bitcoind_implementation == 'core' else _knots_binaries }}"

    - name: "Test that binaries were copied correctly for Bitcoin v{{ bitcoind_version }}"
      ansible.builtin.assert:
        that:
          - item.stat.exists
          - item.stat.executable
          - item.stat.pw_name == 'root'
          - item.stat.gr_name == 'root'
          - item.stat.mode == '0755'
      with_items: "{{ bitcoind_bins.results }}"
