---
- name: Verify
  hosts: all
  become: true
  gather_facts: false
  vars:
    bitcoind_version: 26.0

  tasks:
    - name: "Retrieve information from /usr/local/bitcoin-core-{{ bitcoind_version }}"
      stat:
        path: "/usr/local/bitcoin-core-{{ bitcoind_version }}"
      register: bitcoind_directory

    - name: "Test that Bitcoin Core v{{ bitcoind_version }} directory was created correctly"
      assert:
        that:
          - bitcoind_directory.stat.exists
          - bitcoind_directory.stat.isdir
          - bitcoind_directory.stat.pw_name == 'bitcoin'
          - bitcoind_directory.stat.gr_name == 'bitcoin'
